In [19]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import random

In [20]:
df = pd.read_csv(r'C:\Users\stany\OneDrive\Desktop\Diamonds Set\diamonds.csv')
print(df)

       Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34
...           ...    ...        ...   ...     ...    ...    ...    ...   ...
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83

          y     z
0      3.98  2.43
1      3.84  2.31
2      4.07  2.31
3      4.23  2.63
4      4.35  2.75
...     ...   ...
53935  5.76  3.50
53936  5.75  3.61
53937  5.68  3.56
53938  6.12  3.74
53939  5.87  3.64

[53940 rows x 11 columns]

In [21]:
# df = pd.read_csv(r'C:\Users\stany\OneDrive\Desktop\Air Quality\AirQualityUCI.csv')
# print(df)
print(df.head())

   Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35

      z
0  2.43
1  2.31
2  2.31
3  2.63
4  2.75

In [22]:
df.dtypes

Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [23]:
#Check if there are any NAN values in the dataset

df.isnull().values.any()

False

In [24]:
cut = df['cut']

In [25]:
#one hot encode the columns that need to be changed
# 0=Ideal, 1=Premium, 2=Good, 3=Very Good, 4=fair
df['cut'] = pd.factorize(df['cut'])[0]
df['cut']

0        0
1        1
2        2
3        1
4        2
        ..
53935    0
53936    2
53937    3
53938    1
53939    0
Name: cut, Length: 53940, dtype: int64

In [26]:
color = df['color']

In [27]:
# E=0, I=1, J=2, H=3, F=4, G=5, D=6 
df['color'] = pd.factorize(df['color'])[0]
df['color']

0        0
1        0
2        0
3        1
4        2
        ..
53935    6
53936    6
53937    6
53938    3
53939    6
Name: color, Length: 53940, dtype: int64

In [28]:
clarity = df['clarity']

In [29]:
# SI2=0, SI1=1, VS1=2, VS2=3, VVS2=4, VVS1=5, I1=6, IF=7
df['clarity'] = pd.factorize(df['clarity'])[0]
df['clarity']

0        0
1        1
2        2
3        3
4        0
        ..
53935    1
53936    1
53937    1
53938    0
53939    0
Name: clarity, Length: 53940, dtype: int64

In [30]:
df.pop(df.columns[0])
df

       carat  cut  color  clarity  depth  table  price     x     y     z
0       0.23    0      0        0   61.5   55.0    326  3.95  3.98  2.43
1       0.21    1      0        1   59.8   61.0    326  3.89  3.84  2.31
2       0.23    2      0        2   56.9   65.0    327  4.05  4.07  2.31
3       0.29    1      1        3   62.4   58.0    334  4.20  4.23  2.63
4       0.31    2      2        0   63.3   58.0    335  4.34  4.35  2.75
...      ...  ...    ...      ...    ...    ...    ...   ...   ...   ...
53935   0.72    0      6        1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72    2      6        1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70    3      6        1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    1      3        0   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75    0      6        0   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [31]:
corr = df.corr()
corr.style.background_gradient(cmap='BrBG_r')

In [32]:
from sklearn.model_selection import train_test_split
y = df['price']
col = 'price'
X = df.loc[:, df.columns != col]

rem_X, test_X, rem_y, test_y = train_test_split(X,y, test_size=0.1, random_state=42, shuffle=True)
train_X, valid_X, train_y, valid_y = train_test_split(rem_X, rem_y, test_size=0.2)

In [33]:
print(test.shape)
print(train.shape)
print(valid.shape)

NameError: name 'test' is not defined

In [34]:
# y_train = train['price']
# X_train = train.drop('price', inplace=True, axis=1)
# y_valid = valid['price']
# X_valid = valid.drop('price', inplace=True, axis=1)
# y_test = test['price']
# X_test = test.drop('price', inplace=True, axis=1)

In [35]:
X_train

NameError: name 'X_train' is not defined

In [ ]:
import pickle as pk
from sklearn.ensemble import GradientBoostingRegressor
n = 20
compiled_models = []


losss = ['squared_error', 'absolute_error', 'huber', 'quantile']
learning_rates = [0.1, 0.2, 0.3, 0.5]
n_estimatorss = [100, 200, 300, 400]
subsamples = [0.01, 0.5, 0.99]
criterions = ['friedman_mse', 'squared_error']
max_depths = [3, 5, 7]
max_featuress = ['auto', 'sqrt', 'log2']
warm_starts = [True, False]

counter = 0

for loss in losss:
    for learning_rate in learning_rates:
        for n_estimators in n_estimatorss:
            for subsample in subsamples:
                for criterion in criterions:
                    for max_depth in max_depths:
                        for max_features in max_featuress:
                            for warm_start in warm_starts:
                        
                                print(f"Compiled Model: {counter}\n")

                                try:
                                    model = GradientBoostingRegressor(loss=loss, 
                                                               learning_rate = learning_rate, 
                                                               n_estimators = n_estimators, 
                                                               subsample = subsample, 
                                                               criterion = criterion, 
                                                               max_depth = max_depth, 
                                                               max_features = max_features, 
                                                               warm_start = warm_start).fit(train_X, train_y)
                                except:
                                    counter += 1
                                    continue

                                compiled_models.append([float(model.score(valid_X, valid_y)), model])
                                counter += 1
                        
                        
compiled_models.sort(key=lambda row: (row[0]))
compiled_models = compiled_models[::-1]
compiled_models = compiled_models[0:n]

for i, model in enumerate(compiled_models):
    print(model[0], model[1])
    filename = f'PIKLE/GradientBoostingRegressor_{i}'
    pk.dump(model[1], open(filename, 'wb'))

In [44]:
file = open('PIKLE\GradientBoostingRegressor_0', 'rb')
modelN = pk.load(file)
file.close()

In [45]:
modelN.score(test_X, test_y)

0.9808831923699913